ServerName localhost

<Directory /var/www/html>
    AllowOverride All
    Require all granted
</Directory>

<Directory /var/www/html/uploads>
    AllowOverride None
    Require all denied
</Directory>

<LocationMatch "^/uploads/">
    Require all denied
</LocationMatch>

<Directory /data/verification_uploads>
    AllowOverride None
    Require all denied
</Directory>

<Directory /var/www/html/images/user_uploads>
    AllowOverride None
    Options -ExecCGI
    Require all granted
    php_admin_flag engine off
    RemoveHandler .php .phtml .php3 .php4 .php5 .phar
    <FilesMatch "\.(?i:php[0-9]?|phtml|phar)$">
        Require all denied
    </FilesMatch>
</Directory>

<Directory /data/user_uploads>
    AllowOverride None
    Options -ExecCGI
    Require all granted
    php_admin_flag engine off
    RemoveHandler .php .phtml .php3 .php4 .php5 .phar
    <FilesMatch "\.(?i:php[0-9]?|phtml|phar)$">
        Require all denied
    </FilesMatch>
</Directory>

<Directory /var/www/html/images/admin_uploads>
    AllowOverride None
    Options -ExecCGI
    Require all granted
    php_admin_flag engine off
    RemoveHandler .php .phtml .php3 .php4 .php5 .phar
    <FilesMatch "\.(?i:php[0-9]?|phtml|phar)$">
        Require all denied
    </FilesMatch>
</Directory>

<Directory /data/admin_uploads>
    AllowOverride None
    Options -ExecCGI
    Require all granted
    php_admin_flag engine off
    RemoveHandler .php .phtml .php3 .php4 .php5 .phar
    <FilesMatch "\.(?i:php[0-9]?|phtml|phar)$">
        Require all denied
    </FilesMatch>
</Directory>
